### ISSUE TITLE
Failed to parse score by zold client

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#186]
```
127.0.0.1:4096/0 failed to read, trying again (attempt no.1): JSON can't be nil in nil
127.0.0.1:4096: JSON can't be nil in nil in 11ms
Zold::Score::CantParse: JSON can't be nil in nil
	/var/lib/gems/2.5.0/gems/zold-score-0.4.6/lib/zold/score.rb:122:in `rescue in parse_json'
	/var/lib/gems/2.5.0/gems/zold-score-0.4.6/lib/zold/score.rb:111:in `parse_json'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/commands/remote.rb:321:in `update_one'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/commands/remote.rb:267:in `block (2 levels) in update'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/remotes.rb:197:in `block in iterate'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/hands.rb:88:in `block (3 levels) in exec'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/hands.rb:85:in `loop'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/hands.rb:85:in `block (2 levels) in exec'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/hands.rb:56:in `block (2 levels) in start'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/verbose_thread.rb:41:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/endless.rb:44:in `block in run'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/endless.rb:43:in `loop'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/endless.rb:43:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/hands.rb:55:in `block in start'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/verbose_thread.rb:41:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.22.4/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by DronMDF** [comment]
strength field was not present in score.
